/*
 * Licensed under the EUPL, Version 1.2.
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 */

package net.dries007.tfc.world.feature.vein;

import net.minecraft.core.BlockPos;

/**
 * The instance of an individual vein generated by a {@link VeinFeature}. All we require is that it has a position, any other generation parameters are handled by the feature.
 */
public interface IVein
{
    BlockPos pos();
}
