name: Test 1.21.x

on:
  push:
    branches:
      - 1.21.x
  pull_request:
    branches: [ 1.21.x ]

jobs:
  main:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build, Test, Check Licenses
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      env:
        VERSION: 0.0.0
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r resources/requirements.txt
    - name: Validate Resources
      run: |
        python resources validate
